#define CGA_MEM_START 0xB8000
#define CGA_CST_ROWS 25
#define CGA_CST_COLS 80
#define VGA_CURSOR_POSITION_CMD 0x03D4
#define VGA_CURSOR_POSITION_DATA 0x03D5
#define VGA_CURSOR_CMD_LOWER 0x0F
#define VGA_CURSOR_CMD_UPPER 0x0E

#define DISP_POS_Y_TOP 0
#define DISP_POS_Y_BOTTOM 1
#define DISP_POS_Y_CENTER 2

#define DISP_POS_X_RIGHT 0
#define DISP_POS_X_LEFT 1
#define DISP_POS_X_CENTER 2


#define CGA_COLOR_BLACK 0x00
#define CGA_COLOR_BLUE 0x01
#define CGA_COLOR_GREEN 0X02
#define CGA_COLOR_TEAL 0X03
#define CGA_COLOR_RED 0X04
#define CGA_COLOR_MAGENTA 0X05
#define CGA_COLOR_BROWN 0X06
#define CGA_COLOR_GREY 0X07
// The following colors can only be used as foreground.
#define CGA_COLOR_DARKGREY 0X08
#define CGA_COLOR_LIGHTBLUE 0X09
#define CGA_COLOR_LIGHTGREEN 0X0A
#define CGA_COLOR_LIGHTTEAL 0X0B
#define CGA_COLOR_LIGHTRED 0X0C
#define CGA_COLOR_LIGHTMAGENTA 0X0D
#define CGA_COLOR_YELLOW 0X0E
#define CGA_COLOR_WHITE 0x0F

#define INTRPT_VECT_ADD 0x1000
#define INTRPT_CST_LOWER 0x8E00
#define IRQ_ADD_MASTER 0x21
#define IRQ_ADD_SLAVE 0xA1

#define CLK_FREQ_SET_ENABLE_PORT 0x43
#define CLK_FREQ_SET_ENABLE_VAL 0x34
#define CLK_FREQ_PORT 0x40
#define QUARTZ 0x1234DD
#define CLOCKFREQ 50

#define CMOS_CMD 0x70
#define CMOS_DATA 0x71
#define CMOS_MASK 0x80

#define RTC_CMD_PORT 0x70
#define RTC_DATA 0x71
#define RTC_CMD_SETFREQ 0x8A
#define RTC_CMD_SETSIGTYPE 0x8B

#define DATE_REG_SEC 0
#define DATE_REG_MIN 2
#define DATE_REG_HOUR 4
#define DATE_REG_DAYOFWEEK 6
#define DATE_REG_DAYOFMONTH 7
#define DATE_REG_MONTH 8
#define DATE_REG_YEAR 9
#define DATE_REG_CENT 0x32

#define KEYBOARD_PORT 0x60